### ISSUE TITLE
Pageviews associated with previous page's metadata

### ISSUE THREAD

**Issue by mraakashshah** [Parsely/gatsby-plugin-parsely-analytics#2]
I have noticed behavior where the metadata sent on a pageview event is incorrect. Instead, the metadata is from the previous page.

Effectively, the plug-in is sending a pageview event for before the tracker can execute metadata extraction. In cases of dynamic page refreshes, the metadata that's already there (the previous page's metadata) is sent in the pageview event. Gatsby i
(shout out Josh R for investigating and identifying the failure point when I was at wit's end.)

Luckily, GA has the same issues. I've adapted their solution to our case.

I do not have write permissions for this repo, so I am replicating the work here.

Git hash to cherry pick: `git cherry-pick 6529efc`

`gatsby-browser.js`
```javascript
  [...]
  const params [...]
  [...]

  // wrap in a timeout to give metadata extraction and react-helmet time to execute
  // adapted from gatsby-plugin-google-analytics
  // https://github.com/gatsbyjs/gatsby/blob/2753c4d75e909699348c4f871f0dbfaee7db37ab/packages/gatsby-plugin-google-analytics/src/gatsby-browser.js#L13
  const sendPageView = () => {
    if (options.parselyTrackPageViewExists) {
      window.PARSELY.beacon.trackPageView(params);
    } else {
      window.PARSELY.pageviewQueue.push(params);
    }
  };

  // Minimum delay for reactHelmet's requestAnimationFrame
  setTimeout(sendPageView, 32);

  return null;
};
// EOF
```

Aside: once this is fixed I'll add Parse.ly to the [Gatsby Analytics providers page](https://www.gatsbyjs.org/docs/adding-analytics/).

**Comment by msukmanowsky** [comment]
My bad @mraakashshah, I didn't add Product team as members that can write. Can you try submitting a PR?
